name: minimal_http_client
description: A Dart package based on Dio that provides minimal http client to handle HTTP services requests. A minimal http client libaray for network call 
version: 0.0.2

homepage: https://github.com/champ96k/minimal_http_client

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #network call
  dio: ^5.2.1+1
  dio_http2_adapter: ^2.3.0
  http: ^1.1.0
  pretty_dio_logger: ^1.3.1

  #for querying information about the application package
  package_info: ^2.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter: